// <auto-generated />
using System;
using AllulExpressApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AllulExpressAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102111229_clientpostrelationship2")]
    partial class clientpostrelationship2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AllulExpressApi.Models.Cities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<double>("Driverfee")
                        .HasColumnType("double");

                    b.Property<double>("benifit")
                        .HasColumnType("double");

                    b.Property<double>("totalfee")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("AllulExpressApi.Models.Clients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("double");

                    b.Property<string>("Business")
                        .HasColumnType("longtext");

                    b.Property<double>("Cashmoney")
                        .HasColumnType("double");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Equipment")
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenum1")
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenum2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Returnedposts")
                        .HasColumnType("int");

                    b.Property<DateTime>("Savedate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Totalpaymentpayed")
                        .HasColumnType("double");

                    b.Property<int>("Totalposts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AllulExpressApi.Models.Drivers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Arrivedpost")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IDimageback")
                        .HasColumnType("longtext");

                    b.Property<string>("IDimagefront")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<double>("Paymentpayed")
                        .HasColumnType("double");

                    b.Property<double>("Paymentremained")
                        .HasColumnType("double");

                    b.Property<string>("Phonenum1")
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenum2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Remainedpost")
                        .HasColumnType("int");

                    b.Property<DateTime>("Savedate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Vehicledetail")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("AllulExpressApi.Models.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IDimageback")
                        .HasColumnType("longtext");

                    b.Property<string>("IDimagefront")
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenum1")
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenum2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Savedate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AllulExpressApi.Models.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Businessname")
                        .HasColumnType("longtext");

                    b.Property<bool>("ChangeOrReturn")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Exactaddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Numberofpieces")
                        .HasColumnType("int");

                    b.Property<string>("Phonenum1")
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenum2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Postnum")
                        .HasColumnType("int");

                    b.Property<string>("Poststatus")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<DateTime>("Savedate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Shipmentfee")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CitiesDrivers", b =>
                {
                    b.Property<int>("CitiesId")
                        .HasColumnType("int");

                    b.Property<int>("DriversId")
                        .HasColumnType("int");

                    b.HasKey("CitiesId", "DriversId");

                    b.HasIndex("DriversId");

                    b.ToTable("DriverCities", (string)null);
                });

            modelBuilder.Entity("AllulExpressApi.Models.Posts", b =>
                {
                    b.HasOne("AllulExpressApi.Models.Clients", "Client")
                        .WithMany("Posts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CitiesDrivers", b =>
                {
                    b.HasOne("AllulExpressApi.Models.Cities", null)
                        .WithMany()
                        .HasForeignKey("CitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AllulExpressApi.Models.Drivers", null)
                        .WithMany()
                        .HasForeignKey("DriversId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AllulExpressApi.Models.Clients", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
